#!/usr/bin/env python3
"""Migrate StoryEventCatalog hardcoded events to StoryEventDef XML Defs.

Reads StoryEventCatalog.cs, extracts all static readonly StoryEventSpec
fields, and writes them as RimWorld-compatible StoryEventDef XML entries.

Usage: python3 scripts/migrate_catalog_to_xml.py [--dry-run]
"""
import re
import sys
import os

CATALOG_PATH = "mods/05-Rimconemy-Infected-Automation/Source/Story/StoryEventCatalog.cs"
OUTPUT_DIR = "mods/05-Rimconemy-Infected-Automation/Defs/StoryEvents"

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated StoryEventDefs — migrated from StoryEventCatalog.cs
  Owner: Infected & Automation (Package 05)

  Each entry was hardcoded in SeedHardcodedCatalog(). This XML is the
  declarative source of truth. Override via PatchOperations.

  Generated by: scripts/migrate_catalog_to_xml.py
-->
<Defs>
"""

FOOTER = "\n</Defs>\n"


def extract_event_blocks(text):
    """Extract each `public static readonly StoryEventSpec Name = new ... { ... };` block."""
    pattern = r'public static readonly StoryEventSpec (\w+)\s*=\s*new StoryEventSpec\s*\{([^}]*(?:\{[^}]*\}[^}]*)*)\};'
    # Simplified: find blocks from "public static readonly" to "};" at matching brace depth.
    results = []
    pos = 0
    while True:
        m = re.search(r'public static readonly StoryEventSpec (\w+)\s*=\s*new StoryEventSpec\s*\{', text[pos:])
        if not m:
            break
        name = m.group(1)
        start = pos + m.start()
        body_start = pos + m.end() - 1  # position of opening {
        # Find matching }
        depth = 1
        i = body_start + 1
        while i < len(text) and depth > 0:
            if text[i] == '{':
                depth += 1
            elif text[i] == '}':
                depth -= 1
            i += 1
        body = text[body_start:i]
        results.append((name, body))
        pos = i
    return results


def extract_field(body, field_name, is_string=False, is_float=False, is_int=False):
    """Extract a simple field value from the body."""
    if is_float:
        m = re.search(rf'{field_name}\s*=\s*([0-9]+(?:\.[0-9]+)?)f?', body)
    elif is_int:
        m = re.search(rf'{field_name}\s*=\s*(\d+)', body)
    else:
        m = re.search(rf'{field_name}\s*=\s*"([^"]*)"', body)
    if m:
        return m.group(1)
    return None


def extract_dict(body, field_name):
    """Extract a Dictionary<string, float> block. Returns list of "key=value" strings."""
    # Find the Dictionary block
    pattern = rf'{field_name}\s*=\s*new Dictionary<string,\s*float>\s*\{{([^}}]*(?:\{{[^}}]*\}}[^}}]*)*)\}}'
    m = re.search(pattern, body, re.DOTALL)
    if not m:
        return []
    dict_body = m.group(1)
    results = []
    for line in dict_body.split('\n'):
        kv = re.search(r'\{\s*"([^"]+)",\s*([0-9]+(?:\.[0-9]+)?)f?\s*\}', line)
        if kv:
            results.append(f"{kv.group(1)}={kv.group(2)}")
    return results


def extract_list(body, field_name):
    """Extract a list of EventCondition constructor calls. Returns list of expression strings."""
    pattern = rf'{field_name}\s*=\s*new List<EventCondition>\s*\{{([^}}]*(?:\{{[^}}]*\}}[^}}]*)*)\}}'
    m = re.search(pattern, body, re.DOTALL)
    if not m:
        return None
    list_body = m.group(1)
    results = []
    # Match EventCondition.Xxx(...) calls
    for call in re.finditer(r'EventCondition\.(\w+)\((.*?)\)', list_body):
        func = call.group(1)
        args = call.group(2).strip()
        if args:
            results.append(f"{func}({args})")
        else:
            results.append(f"{func}()")
    return results


def extract_choices(body):
    """Extract EventChoice blocks."""
    results = []
    # Find each new EventChoice { ... } block
    pattern = r'new EventChoice\s*\{([^}]*(?:\{[^}]*\}[^}]*)*)\}'
    for m in re.finditer(pattern, body, re.DOTALL):
        choice_body = m.group(1)
        choice_id = extract_field(choice_body, 'ChoiceId')
        label = extract_field(choice_body, 'Label')
        effects = extract_list(choice_body, 'Effects')
        if choice_id:
            results.append((choice_id, label, effects or []))
    return results


def escape_xml(s):
    if s is None:
        return ""
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def build_xml_entry(name, body, event_id):
    """Build a StoryEventDef XML entry from extracted field values."""
    event_family = extract_field(body, 'EventFamily')
    label = extract_field(body, 'Label')
    description = extract_field(body, 'Description')
    letter_label = extract_field(body, 'LetterLabel')
    letter_text = extract_field(body, 'LetterText')
    text_key = extract_field(body, 'TextKey')
    escalation_band = extract_field(body, 'EscalationBand', is_int=True) or "1"
    escalation_modifier = extract_field(body, 'EscalationModifier', is_float=True) or "0"
    determinism_key = extract_field(body, 'DeterminismKeyTemplate') or ""
    event_version = extract_field(body, 'EventVersion', is_int=True) or "1"

    weights = extract_dict(body, 'Weights')
    cooldowns = extract_dict(body, 'CooldownsDays')
    prerequisites = extract_list(body, 'Prerequisites') or []
    exclusions = extract_list(body, 'Exclusions') or []
    choices = extract_choices(body)
    follow_up_ids = extract_list(body, 'FollowUpIds')

    lines = []
    lines.append(f'  <Rimconemy.InfectedAutomation.Story.StoryEventDef>')
    lines.append(f'    <defName>{event_id}</defName>')
    lines.append(f'    <eventVersion>{event_version}</eventVersion>')
    if event_family:
        lines.append(f'    <eventFamily>{event_family}</eventFamily>')
    if label:
        lines.append(f'    <label>{escape_xml(label)}</label>')
    if description:
        lines.append(f'    <description>{escape_xml(description)}</description>')
    lines.append(f'    <escalationBand>{escalation_band}</escalationBand>')
    lines.append(f'    <escalationModifier>{escalation_modifier}</escalationModifier>')
    if letter_label:
        lines.append(f'    <letterLabel>{escape_xml(letter_label)}</letterLabel>')
    if letter_text:
        lines.append(f'    <letterText>{escape_xml(letter_text)}</letterText>')
    if text_key:
        lines.append(f'    <textKey>{text_key}</textKey>')
    if determinism_key:
        lines.append(f'    <determinismKey>{determinism_key}</determinismKey>')

    if weights:
        lines.append(f'    <weights>')
        for w in weights:
            lines.append(f'      <li>{w}</li>')
        lines.append(f'    </weights>')

    if cooldowns:
        lines.append(f'    <cooldownDays>')
        for c in cooldowns:
            lines.append(f'      <li>{c}</li>')
        lines.append(f'    </cooldownDays>')

    if prerequisites:
        lines.append(f'    <prerequisites>')
        for p in prerequisites:
            lines.append(f'      <li>{escape_xml(p)}</li>')
        lines.append(f'    </prerequisites>')

    if exclusions:
        lines.append(f'    <exclusions>')
        for e in exclusions:
            lines.append(f'      <li>{escape_xml(e)}</li>')
        lines.append(f'    </exclusions>')

    if choices:
        lines.append(f'    <choices>')
        for cid, clabel, ceffects in choices:
            lines.append(f'      <li Class="Rimconemy.InfectedAutomation.Story.StoryEventChoiceDef">')
            lines.append(f'        <choiceId>{cid}</choiceId>')
            if clabel:
                lines.append(f'        <label>{escape_xml(clabel)}</label>')
            if ceffects:
                lines.append(f'        <effects>')
                for e in ceffects:
                    lines.append(f'          <li>{escape_xml(e)}</li>')
                lines.append(f'        </effects>')
            lines.append(f'      </li>')
        lines.append(f'    </choices>')

    if follow_up_ids:
        lines.append(f'    <followUpIds>')
        for f in follow_up_ids:
            lines.append(f'      <li>{f}</li>')
        lines.append(f'    </followUpIds>')

    lines.append(f'  </Rimconemy.InfectedAutomation.Story.StoryEventDef>')
    return '\n'.join(lines)


def main():
    dry_run = '--dry-run' in sys.argv

    if not os.path.exists(CATALOG_PATH):
        print(f"ERROR: {CATALOG_PATH} not found", file=sys.stderr)
        sys.exit(1)

    with open(CATALOG_PATH, 'r') as f:
        text = f.read()

    events = extract_event_blocks(text)
    print(f"Extracted {len(events)} events from StoryEventCatalog.cs")

    # Map field names to event IDs
    id_map = {}
    pos = 0
    while True:
        m = re.search(r'public static readonly StoryEventSpec (\w+)\s*=', text[pos:])
        if not m:
            break
        field_name = m.group(1)
        # Find the EventId line in the following block
        block_end = text.find('};', pos + m.start())
        if block_end > 0:
            block_text = text[pos + m.start():block_end]
            eid = extract_field(block_text, 'EventId')
            if eid:
                id_map[field_name] = eid
        pos += m.end()

    xml_entries = []
    for name, body in events:
        event_id = id_map.get(name, f"rimconemy.unknown.{name.lower()}")
        entry = build_xml_entry(name, body, event_id)
        xml_entries.append(entry)
        print(f"  {name} → {event_id}")

    output = HEADER + '\n\n'.join(xml_entries) + FOOTER

    if dry_run:
        print(f"\nDRY RUN — would write {len(xml_entries)} events to XML")
        print(output[:2000] + "\n... (truncated)")
    else:
        os.makedirs(OUTPUT_DIR, exist_ok=True)
        out_path = os.path.join(OUTPUT_DIR, "StoryEvents_Migrated.xml")
        with open(out_path, 'w') as f:
            f.write(output)
        print(f"\nWritten {len(xml_entries)} StoryEventDefs to {out_path}")
        print(f"File size: {len(output)} chars")


if __name__ == '__main__':
    main()
